/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PixelGardenInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allowedStates"
      | "getAllowedStates"
      | "getPixel"
      | "getTopStates"
      | "height"
      | "isValidState"
      | "owner"
      | "renounceOwnership"
      | "setPixel"
      | "stateKey"
      | "transferOwnership"
      | "trustToken"
      | "width"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "OwnershipTransferred" | "PixelChanged"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "allowedStates",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllowedStates",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPixel",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTopStates",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "height", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isValidState",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setPixel",
    values: [BigNumberish, BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "stateKey", values: [string]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "trustToken",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "width", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "allowedStates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllowedStates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPixel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTopStates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "height", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isValidState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPixel", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stateKey", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "trustToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "width", data: BytesLike): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PixelChangedEvent {
  export type InputTuple = [
    x: BigNumberish,
    y: BigNumberish,
    oldState: BytesLike,
    newState: BytesLike,
    actedState: BytesLike,
    amount: BigNumberish,
    actor: AddressLike
  ];
  export type OutputTuple = [
    x: bigint,
    y: bigint,
    oldState: string,
    newState: string,
    actedState: string,
    amount: bigint,
    actor: string
  ];
  export interface OutputObject {
    x: bigint;
    y: bigint;
    oldState: string;
    newState: string;
    actedState: string;
    amount: bigint;
    actor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PixelGarden extends BaseContract {
  connect(runner?: ContractRunner | null): PixelGarden;
  waitForDeployment(): Promise<this>;

  interface: PixelGardenInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allowedStates: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getAllowedStates: TypedContractMethod<[], [string[]], "view">;

  getPixel: TypedContractMethod<
    [x: BigNumberish, y: BigNumberish],
    [[string, bigint] & { current: string; currentStake: bigint }],
    "view"
  >;

  getTopStates: TypedContractMethod<
    [x: BigNumberish, y: BigNumberish, k: BigNumberish],
    [[string[], bigint[]] & { states: string[]; stakes: bigint[] }],
    "view"
  >;

  height: TypedContractMethod<[], [bigint], "view">;

  isValidState: TypedContractMethod<[state: BytesLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setPixel: TypedContractMethod<
    [x: BigNumberish, y: BigNumberish, state: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  stateKey: TypedContractMethod<[name: string], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  trustToken: TypedContractMethod<[], [string], "view">;

  width: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allowedStates"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getAllowedStates"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getPixel"
  ): TypedContractMethod<
    [x: BigNumberish, y: BigNumberish],
    [[string, bigint] & { current: string; currentStake: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTopStates"
  ): TypedContractMethod<
    [x: BigNumberish, y: BigNumberish, k: BigNumberish],
    [[string[], bigint[]] & { states: string[]; stakes: bigint[] }],
    "view"
  >;
  getFunction(
    nameOrSignature: "height"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isValidState"
  ): TypedContractMethod<[state: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPixel"
  ): TypedContractMethod<
    [x: BigNumberish, y: BigNumberish, state: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stateKey"
  ): TypedContractMethod<[name: string], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "trustToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "width"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PixelChanged"
  ): TypedContractEvent<
    PixelChangedEvent.InputTuple,
    PixelChangedEvent.OutputTuple,
    PixelChangedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PixelChanged(uint32,uint32,bytes32,bytes32,bytes32,uint256,address)": TypedContractEvent<
      PixelChangedEvent.InputTuple,
      PixelChangedEvent.OutputTuple,
      PixelChangedEvent.OutputObject
    >;
    PixelChanged: TypedContractEvent<
      PixelChangedEvent.InputTuple,
      PixelChangedEvent.OutputTuple,
      PixelChangedEvent.OutputObject
    >;
  };
}
